### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by johnbent** [jonashackt/plantuml-markdown#1]
Hello, 

This isn't actually an Issue but I don't know another way to communicate with you and thank you for this repo which we are now very happily using in our project: https://github.com/Seagate/cortx/blob/main/doc/images/plantuml/README.md.

Thanks!

Please feel free to close this Issue.

John

**Comment by jonashackt** [comment]
Hey @johnbent , thanks for your great feedback! Really great to see, that my repo was of help for you 👍 Cheers, Jonas
